name = "Eterm"
uuid = "31f415ca-2d2d-11e9-05ad-e37ee3ba8a1a"
authors = ["Helge Eichhorn <git@helgeeichhorn.de>"]
version = "0.1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
