name = "ErlangTerm"
uuid = "c473b343-35cb-5d8e-bb5e-386e80ca8a60"
authors = ["Helge Eichhorn <git@helgeeichhorn.de>"]
version = "0.1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
